"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](gray_5)\
$os\
$username\
[](bg:orange fg:gray_5)\
$directory\
[](fg:orange bg:green)\
$git_branch\
$git_status\
[](fg:green bg:blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$rlang\
[](fg:blue bg:purple)\
$docker_context\
$conda\
$pixi\
[](fg:purple bg:gray_2)\
$time\
[ ](fg:gray_2)\n \
[󱞪](fg:white) \
"""

# https://developer.apple.com/design/
# human-interface-guidelines/color
palette = "apple_dark"

[palettes.apple_dark]
red = "#ffs0045"
orange = "#ff8b2a"
yellow = "#ffde00"
green = "#00e151"
mint = "#00e4c1"
teal = "#00d7e0"
cyan = "#00d3ff"
blue = "#007eff"
indigo = "#8500ff"
purple = "#ff00f5"
pink = "#ff005f"
brown = "#c28864"
gray_1 = "#8d8c92"
gray_2 = "#636366"
gray_3 = "#4a494b"
gray_4 = "#3d3c3e"
gray_5 = "#303032"
gray_6 = "#222123"
white = "#ffffff"
black = "#000000"

[os]
disabled = false
style = "bg:gray_5 fg:white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:gray_5 fg:white"
style_root = "bg:gray_5 fg:white"
format = '[ $user ]($style)'

[directory]
style = "fg:white bg:orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](bg:green fg:white)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](bg:green fg:white)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[cpp]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[java]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[rlang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:white bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $context) ](fg:#white bg:purple)]($style)'

[conda]
style = "bg:purple"
format = '[[ $symbol( $environment) ](fg:#white bg:purple)]($style)'

[pixi]
style = "bg:purple"
format = '[[ $symbol( $version)( $environment) ](fg:white bg:purple)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:gray_2"
format = '[[  $time ](fg:white bg:gray_2)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
