"$schema" = 'https://starship.rs/config-schema.json'

# https://catppuccin.com/palette/
palette = "catppuccin_latte"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext_1 = "#5c5f77"
subtext_0 = "#6c6f85"
overlay_2 = "#7c7f93"
overlay_1 = "#8c8fa1"
overlay_0 = "#9ca0b0"
surface_2 = "#acb0be"
surface_1 = "#bcc0cc"
surface_0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
